name: Daily Portfolio Check

on:
  schedule:
    - cron: '0 18 * * *'  # 1PM CDT
  workflow_dispatch:

jobs:
  trigger_daily_check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger /daily-check
        run: |
          curl -X GET https://your-app.onrender.com/daily-check
