name: Afternoon Trade Algo

on:
  schedule:
    - cron: '0 20 * * *'  # 3PM CDT
  workflow_dispatch:

jobs:
  trigger_afternoon_trade:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger /run-afternoon-trade
        run: |
          curl -X GET https://slack-bot-xg1w.onrender.com/run-afternoon-trade
