name: Daily Portfolio Check

on:
  schedule:
    - cron: '*/1 * * * *'  # every minute
  workflow_dispatch:

jobs:
  trigger_daily_check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger /daily-check
        run: |
          curl -X GET https://slack-bot-xg1w.onrender.com/daily-check
