name: Cron Test

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo time
        run: echo "Cron triggered at $(date)"
